# Numpy
Assignment Questions

**1.  What is a Python library? Why do we use Python libraries?**
> Python libraries are a collection of related modules that contain bundles of codes that can be used in different programs. Making use of Python libraries makes it convenient for the programmer as they wouldn’t have to write the same code multiple times for different programs.  Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.







**2. What is the difference between Numpy array and List?**

> Lists and arrays are two of the most widely used data structures in Python. A list in Python is simply a collection of objects. These objects can be integers, floating point numbers, strings, boolean values or even other data structures like dictionaries. An array, specifically a Python NumPy array, is similar to a Python list. The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects. Because operations like calculating mean or sum are much faster on NumPy arrays, these data structures are more common in contexts where speed performance is a priority.



**3. Find the shape, size and dimension of the following array?**
> [[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]



In [3]:
import numpy as np
a=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print("The shape of above array is ", np.shape(a))
print("The size of above array is ", np.size(a))
print("The dimension of above array is ", a.ndim)

The shape of above array is  (3, 4)
The size of above array is  12
The dimension of above array is  2


**4. Write python code to access the first row of the following array?**
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
a=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
np.array(a[0])

array([1, 2, 3, 4])

**5. How do you access the element at the third row and fourth column from the given numpy array?**
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
a=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
np.array(a[2,3])

array(12)

**6. Write code to extract all odd-indexed elements from the given numpy array?**
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
a=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(a[:, 1::2])


[[ 2  4]
 [ 6  8]
 [10 12]]


**7. How can you generate a random 3x3 matrix with values between 0 and 1?**




In [13]:
np.random.rand(3, 3)

array([[0.86164753, 0.19447671, 0.07077832],
       [0.96867749, 0.38463611, 0.50080429],
       [0.03550228, 0.72781902, 0.64428526]])

**8. Describe the difference between np.random.rand and np.random.randn?**
> The key difference between np.random.rand and np.random.randn in NumPy lies in the type of random numbers they generate:

**np.random.rand:**

This function generates samples from a uniform distribution between 0 (inclusive) and 1 (exclusive). This means each number has an equal probability of appearing between 0 and 1.
The shape of the output array can be specified as arguments. For example, np.random.rand(3, 4) will generate a 3x4 array of random values between 0 and 1.

**np.random.randn:**

This function generates samples from the standard normal distribution, also known as the Gaussian distribution. This distribution has a mean of 0 and a standard deviation of 1.
Most of the generated values will be close to 0, with fewer values farther away on either side.
Similar to rand, you can specify the desired shape of the output array.




In [14]:
np.random.rand(3, 3)

array([[0.66822391, 0.13612333, 0.97462152],
       [0.45775935, 0.0492768 , 0.539311  ],
       [0.12387152, 0.76454327, 0.71280389]])

In [15]:
np.random.randn(3, 3)

array([[-1.04351953, -1.88745042,  0.59623888],
       [-0.8914016 ,  0.61825038, -1.16352214],
       [ 1.40133862,  0.57566803,  2.08778706]])

**9. Write code to increase the dimension of the following array?**
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [23]:
a=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(a)
print(" Dimension before expansion is ",np.ndim(a))

b=np.expand_dims(a, axis=0)
print(" Dimension before expansion is ",np.ndim(b))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 Dimension before expansion is  2
 Dimension before expansion is  3


**10. How to transpose the following array in NumPy?**
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [24]:
a=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [27]:
a=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
transposed_array = np.transpose(a)
transposed_array

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

**11. Consider the following matrix:**
> Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

> Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]



>Perform the following operation using Python:

1.    Index Wise Multiplication
2.    Matrix Multiplication
3.   Add both the matrix
4.   Subtract B from A
5.   Divide Matrix B by A
























In [34]:
A=np.array([[1, 2, 3], [5, 6, 7],[9, 10, 11]])
B=np.array([[1, 2, 3] ,[5, 6, 7],[9, 10, 11]])
print(A)
print()
print(B)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [35]:
# Index Wise Multiplication
A*B

array([[  1,   4,   9],
       [ 25,  36,  49],
       [ 81, 100, 121]])

In [36]:
# Matrix Multiplication
A @ B

array([[ 38,  44,  50],
       [ 98, 116, 134],
       [158, 188, 218]])

In [37]:
# Add both the matrix
A + B

array([[ 2,  4,  6],
       [10, 12, 14],
       [18, 20, 22]])

In [38]:
# Subtract B from A
B- A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
# Divide Matrix B by A
B/A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**12. Which function in Numpy can be used to swap the byte order of an array?**


> In NumPy, the primary function for swapping the byte order of an array is **np.ndarray.byteswap().**



In [40]:
import numpy as np

# Create an array with integers for demonstration
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
swapped_array = original_array.byteswap()

print("Original array:")
print(original_array)
print("\nSwapped array:")
print(swapped_array)


Original array:
[1 2 3 4]

Swapped array:
[16777216 33554432 50331648 67108864]


**13. What is the significance of the np.linalg.inv function?**

> The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix



In [41]:
A = np.array([[2, 1],
              [7, 4]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Original matrix:")
print(A)

print("\nInverse matrix:")
print(A_inv)


Original matrix:
[[2 1]
 [7 4]]

Inverse matrix:
[[ 4. -1.]
 [-7.  2.]]


**14. What does the np.reshape function do, and how is it used?**

>
The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with a specified shape, and the total number of elements in the reshaped array remains the same as the original array.



In [43]:

# Create a 1D array with 12 elements
original_array = np.arange(12)
print(original_array.ndim)
# Reshape the array to a 3x4 matrix
reshaped_array = np.reshape(original_array, (3, 4))

print("Original array:")
print(original_array)

print("\nReshaped array:")
print(reshaped_array)
print(reshaped_array.ndim)


1
Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


**15. What is broadcasting in Numpy?**

>
Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes and sizes to be combined and operated upon together. This is done in a way that makes it possible to perform element-wise operations between arrays of different shapes, without the need for explicit replication of the smaller array to match the shape of the larger one.

